<?php

namespace Admin\OKWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OKWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OKWRepository extends EntityRepository
{
}
